// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using yuvap.Data;

namespace yuvap.Migrations
{
    [DbContext(typeof(YPContext))]
    partial class YPContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("YuvaParichay.Models.Boy", b =>
                {
                    b.Property<int>("BoyID");

                    b.Property<string>("BoyLikedByConcat");

                    b.Property<string>("MobileNum");

                    b.Property<string>("Name");

                    b.Property<int?>("Pref1");

                    b.Property<int?>("Pref2");

                    b.Property<int?>("Pref3");

                    b.Property<int?>("Pref4");

                    b.Property<int?>("Pref5");

                    b.Property<int?>("Pref6");

                    b.Property<int?>("Pref7");

                    b.Property<int?>("Pref8");

                    b.HasKey("BoyID");

                    b.HasIndex("BoyID")
                        .IsUnique();

                    b.ToTable("Boy");
                });

            modelBuilder.Entity("YuvaParichay.Models.BoyLikedBy", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BoyID");

                    b.Property<int>("GirlID");

                    b.HasKey("ID");

                    b.ToTable("BoyLikedBy");
                });

            modelBuilder.Entity("YuvaParichay.Models.Girl", b =>
                {
                    b.Property<int>("GirlID");

                    b.Property<string>("GirlLikedByConcat");

                    b.Property<string>("MobileNum");

                    b.Property<string>("Name");

                    b.Property<int?>("Pref1");

                    b.Property<int?>("Pref2");

                    b.Property<int?>("Pref3");

                    b.Property<int?>("Pref4");

                    b.Property<int?>("Pref5");

                    b.Property<int?>("Pref6");

                    b.Property<int?>("Pref7");

                    b.Property<int?>("Pref8");

                    b.HasKey("GirlID");

                    b.HasIndex("GirlID")
                        .IsUnique();

                    b.ToTable("Girl");
                });

            modelBuilder.Entity("YuvaParichay.Models.GirlLikedBy", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BoyID");

                    b.Property<int>("GirlID");

                    b.HasKey("ID");

                    b.ToTable("GirlLikedBy");
                });
#pragma warning restore 612, 618
        }
    }
}
